### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by arthur2406** [arthur2406/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by farzq** [comment]
### DONALD TRUMP
* https://www.fb.com/DonaldTrump
* realDonaldTrump@whitehouse.gov
* https://twitter.com/realDonaldTrump
* https://www.instagram.com/realDonaldTrump/

**Comment by farzq** [comment]
<h1 class="name">DONALD TRUMP</h1>
<div class="job">President of United States of America</div>
<ul class="contacts">
 <li><a href="https://www.fb.com/DonaldTrump">DonaldTrump</a></li>
 <li><a href="realDonaldTrump@whitehouse.gov">realDonaldTrump@whitehouse.gov</a></li>
 <li><a href="https://twitter.com/realDonaldTrump">realDonaldTrump</a></li>
 <li><a href="https://www.instagram.com/realDonaldTrump/">realDonaldTrump</a></li>
</ul>
